services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    networks:
      - coolify
    environment:
      TZ: "Asia/Jerusalem"
      # This pulls from the .env file or Coolify Environment Variables tab
      WEBPASSWORD: "${WEBPASSWORD}"
      DNSMASQ_LISTENING: "all"
      FTLCONF_local_ipv4: "${COOL_IP}"
    volumes:
      - "pihole:/etc/pihole"
      - "dnsmasq.d:/etc/dnsmasq.d"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # Port 80 is removed here; use Coolify FQDN settings to access the UI
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
    restart: unless-stopped

networks:
  coolify:
    external: true

volumes:
  pihole:
  dnsmasq.d:
