services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    networks:
      - coolify
    environment:
      TZ: "Asia/Jerusalem"
      WEBPASSWORD: "temporary_test_password"
      DNSMASQ_LISTENING: "all"
      FTLCONF_local_ipv4: 192.168.10.226
    volumes:
      - pihole:/etc/pihole
      - dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
    restart: unless-stopped

networks:
  coolify:
    external: true

volumes:
  pihole:
  dnsmasq.d:
